/* The GIMP -- an image manipulation program
 * Copyright (C) 1995-2003 Spencer Kimball and Peter Mattis
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

/* NOTE: This file is autogenerated by enumcode.pl. */

  { "ADD-WHITE-MASK", 0 },
  { "ADD-BLACK-MASK", 1 },
  { "ADD-ALPHA-MASK", 2 },
  { "ADD-ALPHA-TRANSFER-MASK", 3 },
  { "ADD-SELECTION-MASK", 4 },
  { "ADD-COPY-MASK", 5 },

  { "FG-BG-RGB-MODE", 0 },
  { "FG-BG-HSV-MODE", 1 },
  { "FG-TRANSPARENT-MODE", 2 },
  { "CUSTOM-MODE", 3 },

  { "BRUSH-HARD", 0 },
  { "BRUSH-SOFT", 1 },

  { "FG-BUCKET-FILL", 0 },
  { "BG-BUCKET-FILL", 1 },
  { "PATTERN-BUCKET-FILL", 2 },

  { "CHANNEL-OP-ADD", 0 },
  { "CHANNEL-OP-SUBTRACT", 1 },
  { "CHANNEL-OP-REPLACE", 2 },
  { "CHANNEL-OP-INTERSECT", 3 },

  { "RED-CHANNEL", 0 },
  { "GREEN-CHANNEL", 1 },
  { "BLUE-CHANNEL", 2 },
  { "GRAY-CHANNEL", 3 },
  { "INDEXED-CHANNEL", 4 },
  { "ALPHA-CHANNEL", 5 },

  { "IMAGE-CLONE", 0 },
  { "PATTERN-CLONE", 1 },

  { "NO-DITHER", 0 },
  { "FS-DITHER", 1 },
  { "FSLOWBLEED-DITHER", 2 },
  { "FIXED-DITHER", 3 },

  { "MAKE-PALETTE", 0 },
  { "REUSE-PALETTE", 1 },
  { "WEB-PALETTE", 2 },
  { "MONO-PALETTE", 3 },
  { "CUSTOM-PALETTE", 4 },

  { "NORMAL-CONVOL", 0 },
  { "ABSOLUTE-CONVOL", 1 },
  { "NEGATIVE-CONVOL", 2 },

  { "BLUR-CONVOLVE", 0 },
  { "SHARPEN-CONVOLVE", 1 },

  { "DODGE", 0 },
  { "BURN", 1 },

  { "FOREGROUND-FILL", 0 },
  { "BACKGROUND-FILL", 1 },
  { "WHITE-FILL", 2 },
  { "TRANSPARENT-FILL", 3 },
  { "PATTERN-FILL", 4 },

  { "GRADIENT-SEGMENT-RGB", 0 },
  { "GRADIENT-SEGMENT-HSV-CCW", 1 },
  { "GRADIENT-SEGMENT-HSV-CW", 2 },

  { "GRADIENT-SEGMENT-LINEAR", 0 },
  { "GRADIENT-SEGMENT-CURVED", 1 },
  { "GRADIENT-SEGMENT-SINE", 2 },
  { "GRADIENT-SEGMENT-SPHERE-INCREASING", 3 },
  { "GRADIENT-SEGMENT-SPHERE-DECREASING", 4 },

  { "GRADIENT-LINEAR", 0 },
  { "GRADIENT-BILINEAR", 1 },
  { "GRADIENT-RADIAL", 2 },
  { "GRADIENT-SQUARE", 3 },
  { "GRADIENT-CONICAL-SYMMETRIC", 4 },
  { "GRADIENT-CONICAL-ASYMMETRIC", 5 },
  { "GRADIENT-SHAPEBURST-ANGULAR", 6 },
  { "GRADIENT-SHAPEBURST-SPHERICAL", 7 },
  { "GRADIENT-SHAPEBURST-DIMPLED", 8 },
  { "GRADIENT-SPIRAL-CLOCKWISE", 9 },
  { "GRADIENT-SPIRAL-ANTICLOCKWISE", 10 },

  { "HISTOGRAM-VALUE", 0 },
  { "HISTOGRAM-RED", 1 },
  { "HISTOGRAM-GREEN", 2 },
  { "HISTOGRAM-BLUE", 3 },
  { "HISTOGRAM-ALPHA", 4 },

  { "ALL-HUES", 0 },
  { "RED-HUES", 1 },
  { "YELLOW-HUES", 2 },
  { "GREEN-HUES", 3 },
  { "CYAN-HUES", 4 },
  { "BLUE-HUES", 5 },
  { "MAGENTA-HUES", 6 },

  { "ICON-TYPE-STOCK-ID", 0 },
  { "ICON-TYPE-INLINE-PIXBUF", 1 },
  { "ICON-TYPE-IMAGE-FILE", 2 },

  { "RGB", 0 },
  { "GRAY", 1 },
  { "INDEXED", 2 },

  { "RGB-IMAGE", 0 },
  { "RGBA-IMAGE", 1 },
  { "GRAY-IMAGE", 2 },
  { "GRAYA-IMAGE", 3 },
  { "INDEXED-IMAGE", 4 },
  { "INDEXEDA-IMAGE", 5 },

  { "NORMAL-MODE", 0 },
  { "DISSOLVE-MODE", 1 },
  { "BEHIND-MODE", 2 },
  { "MULTIPLY-MODE", 3 },
  { "SCREEN-MODE", 4 },
  { "OVERLAY-MODE", 5 },
  { "DIFFERENCE-MODE", 6 },
  { "ADDITION-MODE", 7 },
  { "SUBTRACT-MODE", 8 },
  { "DARKEN-ONLY-MODE", 9 },
  { "LIGHTEN-ONLY-MODE", 10 },
  { "HUE-MODE", 11 },
  { "SATURATION-MODE", 12 },
  { "COLOR-MODE", 13 },
  { "VALUE-MODE", 14 },
  { "DIVIDE-MODE", 15 },
  { "DODGE-MODE", 16 },
  { "BURN-MODE", 17 },
  { "HARDLIGHT-MODE", 18 },
  { "SOFTLIGHT-MODE", 19 },
  { "GRAIN-EXTRACT-MODE", 20 },
  { "GRAIN-MERGE-MODE", 21 },
  { "COLOR-ERASE-MODE", 22 },

  { "MASK-APPLY", 0 },
  { "MASK-DISCARD", 1 },

  { "EXPAND-AS-NECESSARY", 0 },
  { "CLIP-TO-IMAGE", 1 },
  { "CLIP-TO-BOTTOM-LAYER", 2 },
  { "FLATTEN-IMAGE", 3 },

  { "MESSAGE-BOX", 0 },
  { "CONSOLE", 1 },
  { "ERROR-CONSOLE", 2 },

  { "OFFSET-BACKGROUND", 0 },
  { "OFFSET-TRANSPARENT", 1 },

  { "ORIENTATION-HORIZONTAL", 0 },
  { "ORIENTATION-VERTICAL", 1 },
  { "ORIENTATION-UNKNOWN", 2 },

  { "PDB-INT32", 0 },
  { "PDB-INT16", 1 },
  { "PDB-INT8", 2 },
  { "PDB-FLOAT", 3 },
  { "PDB-STRING", 4 },
  { "PDB-INT32ARRAY", 5 },
  { "PDB-INT16ARRAY", 6 },
  { "PDB-INT8ARRAY", 7 },
  { "PDB-FLOATARRAY", 8 },
  { "PDB-STRINGARRAY", 9 },
  { "PDB-COLOR", 10 },
  { "PDB-REGION", 11 },
  { "PDB-DISPLAY", 12 },
  { "PDB-IMAGE", 13 },
  { "PDB-LAYER", 14 },
  { "PDB-CHANNEL", 15 },
  { "PDB-DRAWABLE", 16 },
  { "PDB-SELECTION", 17 },
  { "PDB-BOUNDARY", 18 },
  { "PDB-PATH", 19 },
  { "PDB-PARASITE", 20 },
  { "PDB-STATUS", 21 },
  { "PDB-END", 22 },

  { "INTERNAL", 0 },
  { "PLUGIN", 1 },
  { "EXTENSION", 2 },
  { "TEMPORARY", 3 },

  { "PDB-EXECUTION-ERROR", 0 },
  { "PDB-CALLING-ERROR", 1 },
  { "PDB-PASS-THROUGH", 2 },
  { "PDB-SUCCESS", 3 },
  { "PDB-CANCEL", 4 },

  { "PAINT-CONSTANT", 0 },
  { "PAINT-INCREMENTAL", 1 },

  { "PROGRESS-COMMAND-START", 0 },
  { "PROGRESS-COMMAND-END", 1 },
  { "PROGRESS-COMMAND-SET-TEXT", 2 },
  { "PROGRESS-COMMAND-SET-VALUE", 3 },

  { "REPEAT-NONE", 0 },
  { "REPEAT-SAWTOOTH", 1 },
  { "REPEAT-TRIANGULAR", 2 },

  { "ROTATE-90", 0 },
  { "ROTATE-180", 1 },
  { "ROTATE-270", 2 },

  { "RUN-INTERACTIVE", 0 },
  { "RUN-NONINTERACTIVE", 1 },
  { "RUN-WITH-LAST-VALS", 2 },

  { "PIXELS", 0 },
  { "POINTS", 1 },

  { "STACK-TRACE-NEVER", 0 },
  { "STACK-TRACE-QUERY", 1 },
  { "STACK-TRACE-ALWAYS", 2 },

  { "SHADOWS", 0 },
  { "MIDTONES", 1 },
  { "HIGHLIGHTS", 2 },

  { "UNIT-PIXEL", 0 },
  { "UNIT-INCH", 1 },
  { "UNIT-MM", 2 },
  { "UNIT-POINT", 3 },
  { "UNIT-PICA", 4 },
  { "UNIT-END", 5 },
